server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.139.130:8848
    gateway:
      routes:
        - id: item-service       #路由规则id，自定义，唯一，去服务对应application.yaml里看服务名字
          uri: lb://item-service #路由的目标服务，lb表示负载均衡，会从注册中心拉取服务列表
          predicates:            #路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**,/search/** #这里是以请求路径作为判断规则
          filters:
            - AddRequestHeader=bronya, l like her
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
hm:
  jwt:                                #配置有对应的类
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123     #密钥文件的密码
    tokenTTL: 30m
  auth:
    excludePaths:          #不是所有功能都是需要登录以后才能用的
      - /search/**
      - /users/login
      - /items/**
      - /hi
